services:
  app:
    build:
      context: .
      args:
        UID: ${UID:-1000}
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null
    environment:
      - APP_ENV=testing
